vars:
  - TOP: ../..
stages:
  gva:
    cmd: PYTHONPATH=${TOP} python gva.py
    deps:
      - gva.py
      - ${TOP}/pipelines/util.py
      - https://github.com/economic-analytics/edd/raw/main/data/parquet/RGVA_LAD.parquet
    outs:
      - ${TOP}/src/themes/sustainable-growth/_data/gva_lad.csv:
          cache: false